export const EMPLEADO_PROYECTO = "EMPLEADO_PROYECTO";
export const AGREGAR_EMPLEADO = "AGREGAR_EMPLEADO";
export const EMPLEADO_ACTUAL = "EMPLEADO_ACTUAL";
export const ACTUALIZAR_EMPLEADO = "ACTUALIZAR_EMPLEADO";
export const BANDERA_COLOR = "BANDERA_COLOR";
